// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VSlices.Infrastructure.Domain.EntityFrameworkCore.IntegTests;
using VSlices.Infrastructure.Domain.EntityFrameworkCore.IntegTests.DataAccess;

#nullable disable

namespace VSlices.Infrastructure.Domain.EntityFrameworkCore.IntegTests.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240802154336_AddedEntityTable")]
    partial class AddedEntityTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VSlices.Infrastructure.Domain.EntityFrameworkCore.IntegTests.EfCoreRepositoryTests+TEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
